# dsa/apps/myapp-rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-rollout
  namespace: argocd
spec:
  project: myproject
  source:
    repoURL: https://github.com/nehruprakashb123/dsa.git
    targetRevision: argo-rollouts
    path: apps/helm-apps/myapp
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
